apiVersion: v1
kind: Pod
metadata:
  name: "postgres-pod"
  namespace: default
  labels:
    name: "postgres-pod"
    app: "voting-app"
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
    - containerPort: 5432

  - env:
    name: DATABASE_PASSWORD
    value: pr0dr0b0t