apiVersion: v1
kind: Service
metadata:
  name: db
  lables:
    name: db-service
    app: voting-app
  namespace: default
spec:
  selector:
    name: "postgres-pod"
    app: "voting-app"
  ports:
  - port: 5432
    targetPort: 5432