apiVersion: v1
kind: Service
metadata:
  name: redis
  lables:
    name: redis-service
    app: voting-app
  namespace: default
spec:
  selector:
    name: "redis-pod"
    app: "voting-app"
  ports:
  - port: 6379
    targetPort: 6379