apiVersion: v1
kind: Pod
metadata:
  name: "result-app-pod"
  namespace: default
  labels:
    name: "result-app-pod"
    app: "voting-app"
spec:
  containers:
  - name: result-app-pod
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80
