apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  lables:
    name: result-app-service
    app: voting-app
  namespace: default
spec:
  selector:
    name: "result-app-pod"
    app: "result-app"
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80