apiVersion: v1
kind: Pod
metadata:
  name: "voting-app-pod"
  namespace: default
  labels:
    name: "voting-app-pod"
    app: "voting-app"
spec:
  containers:
  - name: voting-app-pod
    image: dockersamples/examplevotingapp_vote
    ports:
    - containerPort: 80
