apiVersion: v1
kind: Pod
metadata:
  name: "worker-app-pod"
  namespace: default
  labels:
    name: "worker-app-pod"
    app: "voting-app"
spec:
  containers:
  - name: worker-app-pod
    image: dockersamples/examplevotingapp_worker
